//
// Created by shecannotsee on 2023/2/14.
//

#ifndef MQTT_LIB_TEST_COMMON_ALGORITHM_SNOWFLAKE_ALGORITHM_HPP_
#define MQTT_LIB_TEST_COMMON_ALGORITHM_SNOWFLAKE_ALGORITHM_HPP_

#endif //MQTT_LIB_TEST_COMMON_ALGORITHM_SNOWFLAKE_ALGORITHM_HPP_
