CXX = g++
CXXFLAGS = -std=c++20 -fmodules-ts

# Source files
SRCS = display.cpp main.cpp

# Object files
OBJS = $(SRCS:.cpp=.o)

# Executable
TARGET = module_test

.PHONY: all clean run

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJS) $(TARGET) ./gcm.cache

run: $(TARGET)
	./$(TARGET)
